# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_packages:
  - covr


install:
- R -e 'install.packages("devtools")' -e 'devtools::install_deps(dep = T)'
- R -e 'install.packages("kableExtra")'

script:
- R CMD build .
- R CMD check *tar.gz

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
